### ISSUE TITLE
User Story :: Login

### ISSUE THREAD

**Issue by kishortare** [varunsinghal/soen-341#1]
**Login User Story**

**Initiator** - Parent or Teacher

**Goal** - Log into Empower application system.
 
As an end user, I want a login screen, so that I can successfully log in with my account, and the app will prompt me if my account is not authenticated. 

**Priority** - 5

**Story points** - 5

**Acceptance Criteria**

- [x] The user input username and password. [#13](https://github.com/varunsinghal/soen-341/issues/13)
- [x] Ensure user authentication is checked. #14 
- [x] the user click on the “log in” button. #15 
- [x] the application prompt “log in successfully” #16 
- [x] User is able to login in to Empower home page.  i.e. His own dashboard #17 
- [x] Display a message when user logs out of the application.  #18 
- [x] Forgot password #19 
- [x] Sign up page for the new users to register as parent or teacher #132

**Comment by varunsinghal** [comment]
Add the sign-up page.

**Comment by admiralponce** [comment]
Closing the issue as sign up page has been added.

**Comment by varunsinghal** [comment]
Open the user story to implement forgot password.

**Comment by admiralponce** [comment]
Implemented forgot password feature for Sprint 5.
