### ISSUE TITLE
User story :: Search

### ISSUE THREAD

**Issue by Mernest** [varunsinghal/soen-341#100]
Initiator - parent or teacher

As a user, I should be able to search for other user profiles and visit their profile.

Story points: 10
Priority: 3

Acceptance criteria
- [x] The search input box for the user to type in the name of the user they want to search #101 
- [x] back-end to receive the request from front-end. #102 
- [x] implement search in repository layer on partial full names. #103 
- [x] Display a result page for the search performed. #104

**Comment by varunsinghal** [comment]
Adding feature to search on groups - universal search option.
