### ISSUE TITLE
User story :: Groups

### ISSUE THREAD

**Issue by Mernest** [varunsinghal/soen-341#110]
Initiator - parent or teacher

As a parent or teacher, user should be able to create groups in the system.

Story points: 10
Priority: 4

Acceptance criteria:
- [x] A link to visit groups should be present in the navigation bar.  #111 
- [x] User can enter the title and description, and submit the form for its creation. #112 
- [x] User can see the list of groups that have been created. #113 
- [x] Owner should be able to add users in the group #180
- [x] User should be able to make posts #182
- [x] User should be able to request to join group #199 
- [x] User should be able to view the members of the group #201 
- [x] User should be able to view the status of each member of the group #202
- [x] Owner should be able to add Admins #208  
- [x] Admins can view the group join requests. #203 
- [x] Admins can accept or remove members from the group. #204 
- [x] Group page which shows quick links #211
