### ISSUE TITLE
User story :: Notifications

### ISSUE THREAD

**Issue by Mernest** [varunsinghal/soen-341#167]
Initiator - parent or teacher

As a parent or teacher, a user should be able to receive the notifications when another user posted on their wall or sends them a message.

Story points: 10

- [x] User should be notified of the messages received #168
- [x] User should be able to view historical notifications #169
- [x] Clear the notification from the tray once the user has clicked on it. #171
- [x] Update the session variable for each new notification #173
- [x] User should be notified of the post made on the wall #176
- [x] User should be notified of the comment made on their wall #178 
- [x]  User should be notified of the friendship request received #226 
- [x] Admins should be notified if the user sent a group join requests #227 
- [x] User should be notified if admin accepts/rejects group join requests #228 
- [x] Tag a user #234
