### ISSUE TITLE
User Story :: UI consistency

### ISSUE THREAD

**Issue by varunsinghal** [varunsinghal/soen-341#185]
Initiator: Parent or Teacher
Parent or teacher should be able to view consistency in the UI as per the below-mentioned task.
Story points: 10
Priority: 6

Acceptance criteria:
- [x] Highlight the active page #186 
- [x] visibile sub menu items for friend section #188 
- [x] visible sub menu items for wall and friend section #190
- [x] visible sub menu item for group section #192  
- [x] reusable user card #194 
- [x] reusable group card #195 
- [ ] public layout background #193
- [ ] Refactoring the public layout #225

**Comment by varunsinghal** [comment]
Reopening the issue as per the enhancements required in login and sign up page.
