### ISSUE TITLE
User Story :: Tags

### ISSUE THREAD

**Issue by varunsinghal** [varunsinghal/soen-341#229]
Initiator: Parent or Teacher

A user should be able to tag other other users in the wall post and group posts.

- [x] A user should be able to tag another user in the wall post #230 
- [x] A user should be able to tag another user in the wall comments #231
- [x] A user should be able to tag other users in the group posts. #232 
- [x] A user should be able to tag other users in the group comments. #233
